name: vetty-ecommerce
on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  rspec:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby 3.0.0
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0.0'
      - name: Install dependencies
        run: |
          cd api
          bundle install
      - name: Set up test database
        run: |
          cd api
          RAILS_ENV=test bundle exec rails db:create db:migrate
      - name: Run tests
        run: |
          cd api
          bundle exec rspec spec
